### ISSUE TITLE
[opinion] trash commands should not look like filenames

### ISSUE THREAD

**Issue by martinetd** [AmineZouitine/rmt.rs#10]
Hello,

this is just a drive-by comment as this was linked on HN, so feel free to ignore as I'm unlikely to keep using it (my solution to this problem is regular filesystem snapshots)

I think trash info/display/flush commands could very well be valid filenames (in particular the two letter aliases, I use t* with short names a lot for temporary files)

In particular that can be bad with wildcards: for example `rmt something ti` will just do `ti` action so `rmt *` is likely to not delete stuff as expected.
(For scripts obviously the same problem as normal rm and friends apply, one should use `rm -- *` or `rm ./*`. Note rmt does not seem to handle `--` either. But for interactive use having commands prefixed with -- is more natural.)

By the way I got panic when restoring the same file multiple times and entering '..' in restore path (aren't I a good monkey):
```
Please enter a new absolute path to restore your element
>> /home/myuser/../
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/trash_manager.rs:270:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
but more importantly it doesn't handle cross dev errors either (leaving aside the fact that one cannot enter a path from /...); it should probably fallback to copy:
```
>> /home/myuser/../../tmp
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 18, kind: CrossesDevices, message: "Invalid cross-device link" }', src/trash_manager.rs:270:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(oh, and max_size in the config doesn't seem to do what I think it should do, but I didn't check if it's actually meant to be used yet nor documented)

Anyway, nitpicks aside it's a good idea; I've seen other implementations but nothing seems to take so good luck :)

**Comment by AmineZouitine** [comment]
Thank you very much for your feedback, I have given all your problems and I will fix it as soon as possible. 
I have many ideas to make the project much more interesting, including adding automatic flush (that the user will have configured), the ability to compress the file before entering the trash etc ...

**Comment by AmineZouitine** [comment]
In the new version 0.1.2, I have fixed the problems of the arguments!  :D

**Comment by martinetd** [comment]
Thanks!
Someone else opened another issue on crossing device, let's close this.
