### ISSUE TITLE
panicking when crossing devices

### ISSUE THREAD

**Issue by neurospochtsfroind** [AmineZouitine/rmt.rs#11]
Removing a file from a different device (ie. ramdisk) causes a crash when calling the `fs::rename` function:

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 18, kind: CrossesDevices, message: "Cross-device link" }', src/trash_manager.rs:83:46

**Comment by AmineZouitine** [comment]
Thank you very much for bringing this problem up, I'm working on it!  :)

**Comment by AmineZouitine** [comment]
The problem should be fixed in version 0.1.8
