### ISSUE TITLE
Consider using the `directories` crate

### ISSUE THREAD

**Issue by StevenBlack** [AmineZouitine/rmt.rs#19]
Hi Amin @AmineZouitine and Adil @AdilZouitine.

I note we're using the `home` crate and that's fine. 

An alternative is the [`directories` crate](https://crates.io/crates/directories) which is really nice. I've used it. What I love about `directories` is it provides easy access to a variety of standard folders in an OS-agnostic way.

For example, `CONFIG` stuff should arguably go in a subfolder within the OS-standard `config_dir` folder.

From the docs:

**`BaseDirs`**

*The intended use case for BaseDirs is to query the paths of user-invisible standard directories that have been defined according to the conventions of the operating system the library is running on.*

`home_dir`
`cache_dir`
`config_dir`
`data_dir`
`data_local_dir`
`executable_dir`
`preference_dir`
`runtime_dir`
`state_dir`

**`UserDirs`**

*The intended use case for UserDirs is to query the paths of user-facing standard directories that have been defined according to the conventions of the operating system the library is running on.*

`home_dir`
`audio_dir`
`desktop_dir`
`document_dir`
`download_dir`
`font_dir`
`picture_dir`
`public_dir`
`template_dir`
`video_dir`

**`ProjectDirs`**

*The intended use case for ProjectDirs is to compute the location of cache, config or data directories for your own application or project, which are derived from the standard directories.*

`cache_dir`
`config_dir`
`data_dir`
`data_local_dir`
`preference_dir`
`runtime_dir`
`state_dir`

**Comment by AdilZouitine** [comment]
Hi @StevenBlack , 

First, I would like to thank you for your interest in the project.

With @AmineZouitine , we have read your proposal and find it very relevant. 
We are doing some refactoring and functional test additions, and then we will replace the `home` crate with `directories`.
 
If you have any other suggestions, please come back to us! 😄
