### ISSUE TITLE
Improve flag ergonomics

### ISSUE THREAD

**Issue by adsick** [AmineZouitine/rmt.rs#25]
I think that `rmt --td` is a little verbose to type, one char flag would be more appropriate (`rmt -x` where x is your letter of choice)

**Comment by AmineZouitine** [comment]
Thanks for your comment, the argument --td means "trash display", --ti means "trash info" and --tf means "trash flush", it's true that using only one letter could be more convenient for users, but for example -d and -i are already used, would you have an idea of a letter that makes sense?

**Comment by adsick** [comment]
I can't say for sure, but something like "list", or "manage" is possible. for "trash info" I would pick "stats".
You can use long variants for clarity and for brevity the short ones.
