### ISSUE TITLE
Request sql improvement 

### ISSUE THREAD

**Issue by AmineZouitine** [AmineZouitine/rmt.rs#28]
File: https://github.com/AmineZouitine/rmt.rs/blob/main/src/data_manager.rs

Some sql queries are not optimized, example : 

```rs
pub fn find_trash_item_by_id(connection: &Connection, is_test: bool, id: i32) -> TrashItem {
    find_all_trash_items(connection, is_test)
        .into_iter()
        .find(|trash_item| trash_item.id == id)
        .unwrap()
}
```
While a where could directly give us the item we want, without retrieving all of them 

Another example in the file https://github.com/AmineZouitine/rmt.rs/blob/main/src/input_manager.rs
line 29

```rs
        data_manager::find_all_trash_items(connection, is_test).len()
```
While a "get_element_count" function by spanking a select COUNT(*) could be faster

**Comment by NCanggoro** [comment]
halo,
is this still available ?
i want to work in this issue

**Comment by AmineZouitine** [comment]
Yes it is still available, moreover it would be interesting to manage the errors better than what I currently do
