### ISSUE TITLE
Change 'flush' commnad key

### ISSUE THREAD

**Issue by lanius412** [AmineZouitine/rmt.rs#43]
I think the flush command should be changed.
https://github.com/AmineZouitine/rmt.rs/blame/d90c3e6ef16623b109142a13165e04a3cf6b5116/src/display_manager.rs#L141
```
display_input("del", "flush"),
```
 Because keyboards below 70% and laptop keyboards do not have a Del key.

**Comment by AmineZouitine** [comment]
Good point, thank you! I will make the necessary modifications !

**Comment by AmineZouitine** [comment]
Ok now user can press 'f' key to do that too
